name: Deploy Docker Image to Azure Web App

on:
  push:
    branches:
      - release
  pull_request:
    branches:
      - main

env:
  AZURE_CONTAINER_REGISTRY: InfratrackMLmodelDeploy
  AZURE_WEBAPP_NAME: infratrack-ml-model #Changed to web app name
  RESOURCE_GROUP: rg-infratrack-backend-prod
  IMAGE_NAME: ${{ env.AZURE_CONTAINER_REGISTRY }}.azurecr.io/projectinfratrack/${{ env.AZURE_WEBAPP_NAME }}:deploy # Image tag, using projectinfratrack repository

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to ACR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.AZURE_CONTAINER_REGISTRY }}.azurecr.io
          username: ${{ secrets.AZURE_REGISTRY_USERNAME }}
          password: ${{ secrets.AZURE_REGISTRY_PASSWORD }}

      - name: Build and push Docker image to ACR
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ env.IMAGE_NAME }}
          file: ./Dockerfile

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure Web App for Containers
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          images: ${{ env.IMAGE_NAME }}
          resource-group: ${{ env.RESOURCE_GROUP }}
